# __Pandas__
* In Python, Pandas is a open source data analysis and manipulation library which is use for structured data(tables, CSV files, databases)
* Pandas mainly use for data cleaning, analyzing and transforming the data.
* It is use in field of data science, machine learning and data analysis

👉 _In Simple words_: Pandas = Excel but more powerfull

In [1]:
import pandas as pd
# Ek directory ko DataFrame me convert karna
data = {
    "name": ['a','b','c','d'],
    "age": [20,21,19,18],
    "address": ['BBK','LKO','GDA','KP']
}
df = pd.DataFrame(data)
df  # isko print ke andar bhi likh sakte hai lekin uske andar likhne par excel wala theme(mzaa) nahi ayega

  name  age address
0    a   20     BBK
1    b   21     LKO
2    c   19     GDA
3    d   18      KP

<h2>Read Data</h2>
<p>
We use <code>pandas.read_csv()</code> function to read the csv file. In the bracket, we put the file path along with a quotation mark, so that pandas will read the file into a data frame from that address. The file path can be either an URL or your local file address.<br>
Because the data does not include headers, we can add an argument <code>headers = None</code>  inside the  <code>read_csv()</code> method, so that pandas will not automatically set the first row as a header.<br>
You can also assign the dataset to any variable you create.
</p>

In [2]:
df = pd.DataFrame({"names" : ['a', 's'], "age" : [100, 99]})
df

  names  age
0     a  100
1     s   99

In [3]:
headers = ["symboling","normalized-losses","make","fuel-type",
           "aspiration", "num-of-doors","body-style","drive-wheels",
           "engine-location","wheel-base", "length","width",
           "height","curb-weight","engine-type","num-of-cylinders",
           "engine-size","fuel-system","bore","stroke",
           "compression-ratio","horsepower","peak-rpm","city-mpg",
           "highway-mpg","price"]
ad = pd.DataFrame(headers)
ad

                    0
0           symboling
1   normalized-losses
2                make
3           fuel-type
4          aspiration
5        num-of-doors
6          body-style
7        drive-wheels
8     engine-location
9          wheel-base
10             length
11              width
12             height
13        curb-weight
14        engine-type
15   num-of-cylinders
16        engine-size
17        fuel-system
18               bore
19             stroke
20  compression-ratio
21         horsepower
22           peak-rpm
23           city-mpg
24        highway-mpg
25              price

- creating dataset
    - dictionary of item 
    - lisk of dictionaries
    - importing dataset as CSV, xlsx etc. formats
- basic insights of dataset
- data selection
    - row wise selection 
    - column wise selection
- cleaning of manipulation