In [1]:
import plotly.express as px
import seaborn as sns

In [2]:
df = sns.load_dataset('car_crashes')    
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [3]:
fig= px.bar(df,x='abbrev',y='total',
            title='total car Accidents by state',
            labels={'abbrev':'state','total':'total accidents'},
)
fig.show()

In [ ]:
# importing plotly.io to save the figure as an image where io stands for input/output
import plotly.io as pio 
pio.write_image(fig, 'total_car_accidents_by_state.png') # saving the figure as

In [20]:
df = sns.load_dataset('car_crashes')
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [6]:
top10 = df.sort_values('ins_premium', ascending=False).head(10)
fig= px.bar(top10,x='abbrev',y='ins_premium',
            title='top 10 states with highest insurance premium',
            labels={'abbrev':'state','ins_premium':'insurance premium'},
            color = 'ins_premium',
            color_continuous_scale=px.colors.sequential.Agsunset,
            template='plotly_dark'
)
fig.show()

In [26]:
fig =px.pie(df.head(10),values = 'speeding', names ='abbrev',
         title='car accidents due to speeding accidents by statee',
         color_discrete_sequence=px.colors.sequential.Darkmint_r,
         template='plotly_dark'
)
fig.update_traces(textposition='inside')
fig.show()

In [8]:
ig = px.scatter(df,x = 'alcohol', y = 'speeding',
                title = 'alcohol vs speeding',
                labels = {'alcohol':'alcohol related accidents',
                          'speeding':'speeding related accidents'}, 
                          color='abbrev',
                          color_discrete_sequence=px.colors.sequential.Agsunset, 
                          template='plotly_dark', 
                          size='total'
)
ig.update_layout(title ={'x':0.5})
ig.show()

In [9]:
import plotly.express as px
import seaborn as sns

tips = sns.load_dataset("tips")

fig = px.scatter(
    tips, 
    x="total_bill", 
    y="tip", 
    template='plotly_dark',
    title="Scatter plot of Total Bill vs Tip",
    labels={"total_bill": "Total Bill ($)", "tip": "Tip ($)"}
)

fig.show()

In [10]:
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
datasets = sns.get_dataset_names()
datasets

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [12]:
data = sns.load_dataset("taxis")
data.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [13]:
import plotly.express as px
import seaborn as sns

# Load taxis dataset
data = sns.load_dataset("taxis")

# Scatter plot
fig = px.scatter(
    data,
    x="distance",
    y="fare",
    color="passengers",   # color points by number of passengers
    template='plotly_dark',     # add dark theme
    size="tip",           # bubble size = tip amount
    title="Taxi Fare vs Distance (Bubble size = Tip, Color = Passengers)",
    labels={"fare": "Fare ($)", "distance": "Distance (miles)"}
)

fig.show()

In [29]:
fig = px.histogram(
    data,
    x="fare",
    nbins=50,
    title="Distribution of Taxi Fares",
    template='plotly_dark', 
    labels={"fare": "Fare ($)"},
    color_discrete_sequence=px.colors.sequential.Agsunset
    
)
fig.show()

In [15]:
fig = px.box(
    data,
    x="pickup_zone",
    y="tip",
    title="Tip Distribution by Pickup Zone",
    template='plotly_dark', 
    labels={"pickup_zone": "Pickup Zone", "tip": "Tip ($)"}
    
)
fig.show()

In [16]:
import plotly.express as px
import seaborn as sns

# Load taxis dataset
data = sns.load_dataset("taxis")

# Pie chart of payment types
fig = px.pie(
    data,
    names="payment",   # column for categories
    template='plotly_dark', 
    title="Distribution of Payment Methods in Taxi Rides"
)

fig.show()

In [17]:
fig = px.pie(
    data,
    names="passengers",  # group by number of passengers
    template='plotly_dark', 
    title="Share of Taxi Rides by Number of Passengers"
    
)
fig.show()

In [30]:
# 3d scatter plot
fig = px.scatter_3d(
    data,
    x="distance",
    y="fare",
    z="tip",
    color="passengers",   # color points by number of passengers
    template='plotly_dark',     # add dark theme
    size="tip",           # bubble size = tip amount
    title="3D Scatter of Fare vs Distance vs Tip",
    labels={"fare": "Fare ($)", "distance": "Distance (miles)", "tip": "Tip ($)"}
)   
fig.show()